variables:
- name: BuildParameters.solution
  value: '**\*.sln'

name: 1.0.0$(rev:.r)

trigger:
- main

pool:
  vmImage: windows-latest

steps:
  - task: DotNetCoreCLI@2
    name: "Build_Solution"
    inputs:
      command: 'build'
      projects: $(BuildParameters.solution)
      configuration: $(BuildConfiguration)
      arguments: '--configuration $(BuildConfiguration) /p:Version=$(Build.BuildNumber)'
  - task: DotNetCoreCLI@2
    name: "Pack_Project"
    inputs:
      command: 'pack'
      packagesToPack: '**/*.csproj'
      versioningScheme: 'byBuildNumber'
  - task: GitHubRelease@1
    name: "Publish_Release_To_GitHub"
    inputs:
      gitHubConnection: 'GitHub PAT'
      repositoryName: '$(Build.Repository.Name)'
      action: 'create'
      target: '$(Build.SourceVersion)'
      tagSource: 'userSpecifiedTag'
      tag: 'v$(Build.BuildNumber)'
      title: 'v$(Build.BuildNumber) - $(BuildConfiguration) - $(Build.SourceBranchName)'
      changeLogCompareToRelease: 'lastFullRelease'
      changeLogType: 'commitBased'