variables:
- name: BuildParameters.solution
  value: '**\*.sln'

name: v1.0.0$(rev:.r)

trigger:
- main

pool:
  vmImage: windows-latest

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: $(BuildParameters.solution)
  - task: DotNetCoreCLI@2
    inputs:
      command: 'pack'
      packagesToPack: '**/*.csproj'
      versioningScheme: 'off'