variables:
- name: BuildParameters.solution
  value: '**\*.sln'
- name: Major
  value: 1
- name: Minor
  value: 0
- name: Patch
  value: 0

name: v$(Major).$(Minor).$(Patch)$(rev:.r)

trigger:
- main

pool:
  vmImage: windows-latest

steps:
  - task: DotNetCoreCLI@2
    name: "Build_Solution"
    inputs:
      command: 'build'
      projects: $(BuildParameters.solution)
      configuration: $(BuildConfiguration)
  - task: DotNetCoreCLI@2
    name: "Pack_Project"
    inputs:
      command: 'pack'
      packagesToPack: '**/*.csproj'
      versioningScheme: byPrereleaseNumber
      majorVersion: $(Major)
      minorVersion: $(Minor)
      patchVersion: $(Patch)
  - task: GitHubRelease@1
    name: "Publish_Release_To_GitHub"
    inputs:
      gitHubConnection: 'GitHub PAT'
      repositoryName: '$(Build.Repository.Name)'
      action: 'create'
      target: '$(Build.SourceVersion)'
      tagSource: 'userSpecifiedTag'
      tag: '$(Build.BuildNumber)'
      title: '$(Build.BuildNumber) - $(BuildConfiguration) - $(Build.SourceBranchName)'
      changeLogCompareToRelease: 'lastFullRelease'
      changeLogType: 'commitBased'