variables:
- name: BuildParameters.solution
  value: '**\*.sln'

name: $(Major).$(Minor).$(Patch)

trigger:
- main

pool:
  vmImage: windows-latest

steps:
  - task: DotNetCoreCLI@2
    displayName: "Build Solution"
    inputs:
      command: 'build'
      projects: $(BuildParameters.solution)
      configuration: $(BuildConfiguration)
  - task: DotNetCoreCLI@2
    displayName: "Pack Project"
    inputs:
      command: 'pack'
      packagesToPack: '**/*.csproj'
      versioningScheme: byEnvVar
      versionEnvVar: PackageVersion
  - task: GitHubRelease@1
    displayName: "Publish Relase To GitHub"
    inputs:
      gitHubConnection: 'GitHub PAT'
      repositoryName: '$(Build.Repository.Name)'
      action: 'create'
      target: '$(Build.SourceVersion)'
      tagSource: 'userSpecifiedTag'
      tag: '$(BuildNumber)'
      title: '$(BuildNumber) - $(BuildConfiguration) - $(Build.SourceBranchName)'
      changeLogCompareToRelease: 'lastFullRelease'
      changeLogType: 'commitBased'