variables:
- name: BuildParameters.solution
  value: '**\*.sln'
- name: SemVer
  value: '1.0.0'

name: $(SemVer)

trigger:
- main

pool:
  vmImage: windows-latest

steps:
  - task: DotNetCoreCLI@2
    name: "Build_Solution"
    inputs:
      command: 'build'
      projects: $(BuildParameters.solution)
      configuration: $(BuildConfiguration)
  - task: DotNetCoreCLI@2
    name: "Pack_Project"
    inputs:
      command: 'pack'
      packagesToPack: '**/*.csproj'
      versioningScheme: byBuildNumber
  - task: GitHubRelease@1
    name: "Publish_Release_To_GitHub"
    inputs:
      gitHubConnection: 'GitHub PAT'
      repositoryName: '$(Build.Repository.Name)'
      action: 'create'
      target: '$(Build.SourceVersion)'
      tagSource: 'userSpecifiedTag'
      tag: 'v$(Build.BuildNumber)$(rev:.r)'
      title: 'v$(Build.BuildNumber)$(rev:.r) - $(BuildConfiguration) - $(Build.SourceBranchName)'
      changeLogCompareToRelease: 'lastFullRelease'
      changeLogType: 'commitBased'