// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "namespace", Target = "~N:RfmUsb.Net.Exceptions")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "namespace", Target = "~N:RfmUsb.Net.Extensions")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "namespace", Target = "~N:RfmUsb.Net.Ports")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "namespace", Target = "~N:RfmUsb.Net.Io")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "namespace", Target = "~N:RfmUsb.Net")]

[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "type", Target = "~T:RfmUsb.Net.Exceptions.RfmUsbSerialPortOpenFailedException")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "type", Target = "~T:RfmUsb.Net.Exceptions.RfmUsbBufferedIoNotEnabledException")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "type", Target = "~T:RfmUsb.Net.Exceptions.RfmUsbSerialPortNotFoundException")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "type", Target = "~T:RfmUsb.Net.Exceptions.RfmUsbBufferedIoOverflowException")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "type", Target = "~T:RfmUsb.Net.Exceptions.RfmUsbTransmitNotEnabledException")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "type", Target = "~T:RfmUsb.Net.Exceptions.RfmUsbInvalidDeviceTypeException")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "type", Target = "~T:RfmUsb.Net.Exceptions.RfmUsbCommandExecutionException")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "type", Target = "~T:RfmUsb.Net.Exceptions.RfmUsbTransmitException")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "type", Target = "~T:RfmUsb.Net.Exceptions.RfmUsbTimeoutException")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "type", Target = "~T:RfmUsb.Net.OokAverageThresholdFilter")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "type", Target = "~T:RfmUsb.Net.RfmUsbServiceExtensions")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "type", Target = "~T:RfmUsb.Net.OokModulationShaping")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "type", Target = "~T:RfmUsb.Net.OokThresholdDec")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "type", Target = "~T:RfmUsb.Net.Io.RfmUsbStream")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "type", Target = "~T:RfmUsb.Net.RssiSmoothing")]


[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~M:RfmUsb.Net.RfmBase.GetDioMapping(RfmUsb.Net.Dio)~RfmUsb.Net.DioMapping")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~M:RfmUsb.Net.RfmBase.SetDioMapping(RfmUsb.Net.Dio,RfmUsb.Net.DioMapping)")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.Rfm69.TimeoutRssiThreshold")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.RfmBase.DioInterruptMask")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.Rfm69.RssiThreshold")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.RfmBase.LastRssi")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.RfmBase.Rssi")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.RfmBase.RxBw")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.RfmBase.OokFixedThreshold")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.RfmBase.OokAverageThresholdFilter")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.RfmBase.OokModulationShaping")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.RfmBase.OokPeakThresholdStep")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.RfmBase.OcpEnable")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.RfmBase.OcpTrim")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.RfmBase.FskModulationShaping")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.RfmBase.Fei")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~E:RfmUsb.Net.RfmBase.DioInterrupt")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.RfmBase.OokThresholdType")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.RfmBase.OokPeakThresholdDec")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.RfmBase.LnaGainSelect")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.RfmBase.RxBwAfc")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~M:RfmUsb.Net.RfmBase.EnterBootloader")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.Rfm9x.PacketRssi")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.Rfm9x.RssiWideband")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.Rfm9x.TcxoInputOn")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.Rfm9x.LastPacketSnr")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~M:RfmUsb.Net.Rfm69.ExecuteStartRssi")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.Rfm9x.LnaBoostHf")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~M:RfmUsb.Net.Rfm69.SetAesKey(System.Collections.Generic.IEnumerable{System.Byte})")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.Rfm9x.RssiCollisionThreshold")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.Rfm9x.RssiOffset")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.Rfm9x.RssiSmoothing")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.Rfm9x.RssiThreshold")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.Rfm9x.TimeoutRxRssi")]

[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~M:RfmUsb.Net.Rfm9x.ExecuteRestartRxWithoutPllLock")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~M:RfmUsb.Net.Rfm9x.ExecuteRestartRxWithPllLock")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.Rfm9x.OokAverageOffset")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.Rfm9x.IrqFlags")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.Rfm9x.LoraIrqFlags")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.Rfm9x.AgcAutoOn")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.Rfm9x.LoraAgcAutoOn")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.Rfm9x.LoraIrqFlagsMask")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~M:RfmUsb.Net.Rfm9x.ExecuteAgcStart")]


[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.Ports.ISerialPort.DtrEnable")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.Ports.ISerialPort.CtsHolding")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.Ports.ISerialPort.DsrHolding")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.Ports.ISerialPort.RtsEnable")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.Ports.SerialPort.CtsHolding")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.Ports.SerialPort.RtsEnable")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.Ports.SerialPort.DsrHolding")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.Ports.SerialPort.DtrEnable")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.Rfm69.IrqFlags")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.Rfm69.CurrentLnaGain")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~M:RfmUsb.Net.Rfm69.ExecuteFeiStart")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.Rfm69.DccFreq")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.Rfm69.DccFreqAfc")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.Rfm69.AesOn")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:RfmUsb.Net.Rfm69.ContinuousDagc")]
